from collections import deque

stack = []
# stack.append('a')
# stack.append('b')
# stack.append('c')
# stack.append('d')
# stack.append('e')
# print("Initial stack")
# print(stack)
# print('\n')
# stack.pop()
# stack.pop()
# stack.pop()
# print(stack)
# print('\n')

second = deque()
# second.append('a')
# second.append('b')
# second.append('c')
# second.append('d')
# second.append('e')
# print("Second stack")
# print(second)
# print('\n')
# second.pop()
# second.pop()
# second.pop()
# print(second)
